### ISSUE TITLE
'Injured Patient' - How to model 'injury'?

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#10]
We want to indicate that the bearer of this role is an injured organism. How do we model an injured organism? 

* OGMS classifies injuries as material entities and defines 'injury' as "A part of an organism that has undergone a change in structural integrity and has a higher chance of dysfunction or causing dysfunction in another structure." 
* If we use the OGMS term, then 'injured patient role' can write a restriction that says:
'patient role' hasEquivalentClass some ('patient role' and ('inheres in' some ('organism and ('has part' some 'injury'))))

* EFO classifies injuries as dispositions and defines 'injury' as "Damage inflicted on the body as the direct or indirect result of an external force, with or without disruption of structural continuity."
* If we use the EFO term, then the restriction for 'injured patient role' would be:
'patient role' hasEquivalentClass some ('patient role' and ('inheres in' some ('organism and '(is bearer of' some 'injury'))))

**Comment by hoganwr** [comment]
I prefer the OGMS approach.

It's not clear to me how an injury could be a disposition. A disposition to
what process?

Bill

**Comment by aellenhicks** [comment]
That was my initial thought also.

On Tue, Jun 16, 2015 at 3:44 PM, Bill Hogan <notifications@github.com>
wrote:

> I prefer the OGMS approach.
>
> It's not clear to me how an injury could be a disposition. A disposition to
> what process?
>
> Bill
>
> On Tuesday, June 16, 2015, aellenhicks <notifications@github.com> wrote:
>
> > We want to indicate that the bearer of this role is an injured organism.
> > How do we model an injured organism?
> >
> > - OGMS classifies injuries as material entities and defines 'injury'
> > as "A part of an organism that has undergone a change in structural
> > integrity and has a higher chance of dysfunction or causing dysfunction
> in
> > another structure."
> > -
> >
> > If we use the OGMS term, then 'injured patient role' can write a
> > restriction that says:
> > 'patient role' hasEquivalentClass some ('patient role' and ('inheres
> > in' some ('organism and ('has part' some 'injury'))))
> > -
> >
> > EFO classifies injuries as dispositions and defines 'injury' as
> > "Damage inflicted on the body as the direct or indirect result of an
> > external force, with or without disruption of structural continuity."
> > - If we use the EFO term, then the restriction for 'injured patient
> > role' would be: 'patient role' hasEquivalentClass some ('patient role'
> and
> > ('inheres in' some ('organism and '(is bearer of' some 'injury'))))
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ufbmi/OMRSE/issues/10>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufbmi/OMRSE/issues/10#issuecomment-112546513>.
>



-- 
Amanda Hicks, PhD
 Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932 <%28352%29%20294-4197>
f: (352) 273-8703
aehicks@ufl.edu <hoganwr@ufl.edu>

**Comment by aellenhicks** [comment]
'injury' MIREOTed from OGMS, equivalence class restriction added
