### ISSUE TITLE
omrse.owl dead, long live omrse-core.owl?

### ISSUE THREAD

**Issue by turbomam** [ufbmi/OMRSE#100]
As of https://github.com/ufbmi/OMRSE/commit/0441eaddfbab7ea9493ae18b2fa08033ca8832b1 , https://raw.githubusercontent.com/ufbmi/OMRSE/master/omrse/omrse.owl contains 0 classes and is otherwise < 3 KB in size.

On the other hand, https://raw.githubusercontent.com/ufbmi/OMRSE/master/omrse/omrse-core.owl has lots of classes and is 260 KB.

Should I start using omrse-core.owl instead of omrse.owl?

**Comment by hoganwr** [comment]
Mark,

Functionally, yes, the old omrse.owl has been moved to omrse-core.owl.  You
would miss all new modules that get imported into omrse.owl other than
core, however.  Such as omrse-language.owl and the hot-off-the-presses
omrse-education.owl (which is still only on the development branch).

Bill

**Comment by hoganwr** [comment]
I'm assuming your question is answered.  If you have a request for a change, or additional questions, please don't hesitate to start a new issue.
