### ISSUE TITLE
Create class  -  "Education" 

### ISSUE THREAD

**Issue by zhanghansi** [ufbmi/OMRSE#102]
We are planning to build an ontology for the Social Determinants of Health.  We had a meeting with Dr. Hogan to discuss the class definition for one of the determinants - "Education".  We want to reuse this class from OMRSE.  Please create the class for "Education" so that we could reuse it.

**Comment by mbrochhausen** [comment]
Can you please propose a definition? Without one, we do not know which meaning you intend that class to represent.

**Comment by zhanghansi** [comment]
I have provided a list of definitions for Dr. Hogan in the meeting. Dr. Hogan said he will choose one and make an improvement.

**Comment by zhanghansi** [comment]
> Can you please propose a definition? Without one, we do not know which meaning you intend that class to represent.

I have provided a list of definitions for Dr. Hogan in the meeting. Dr. Hogan said he will choose one and make an improvement.

**Comment by mbrochhausen** [comment]
Fair enough
