### ISSUE TITLE
New term request: Cancer summary staging code

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#104]
editor preferred term: Cancer summary staging code
alternative terms: tumor summary staging code
textual definition: An information content entity that is the specified output of cancer summary staging. 
definition source for the textual definition n/a
logical definition (or parent term) information content entity; is_specified_output of some tumor summary staging
example of usage: The cancer summary staging code that is the outcome of the cancer summary staging performed on patient John Doe's clinical picture.
term editor: Mathias Brochhausen

This is a temporary term that we hope will get pickup by OGMS, but we need an IRI for it now.
Term request to OGMS is on the way.

**Comment by CDowland** [comment]
In the logical definition, might it be better to use the preferred term rather than the alternative term?

**Comment by sjbost** [comment]
I thought we had decided to drop "summary" from the term and just use "cancer staging code." Am I incorrect? If so, I need to edit my notes and action items from the meeting.

**Comment by mbrochhausen** [comment]
I think we decided to keep "summary".

**Comment by sjbost** [comment]
Just updated my notes to reflect that we ARE keeping summary.

**Comment by mbrochhausen** [comment]
> In the logical definition, might it be better to use the preferred term rather than the alternative term?

true. we can change when adding the term.

**Comment by dillerm** [comment]
Is this good to go or does it still need further discussion?

**Comment by mbrochhausen** [comment]
Good to go with the change Clint suggested.
