### ISSUE TITLE
Duplicate 'residential facility' classes

### ISSUE THREAD

**Issue by dillerm** [ufbmi/OMRSE#105]
There are currently two classes with the label 'residential facility': [OMRSE_00000108](http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/OMRSE_00000108) and [OMRSE_00000191](http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/OMRSE_00000191).

My proposal is to relabel OMRSE_00000108 as 'residential health care facility'.

**Comment by CDowland** [comment]
I already did this on April 7, and the change is the same one you proposed here. It isn't in the master branch yet, but once the commit is accepted it will be. 

See here: https://github.com/ufbmi/OMRSE/commit/f6e9c91377bce6d25d3f5bff5b21c391cda3223e

**Comment by dillerm** [comment]
Ahh, my bad then!
