### ISSUE TITLE
Term request: 'county smoking survey data', 'county smoking survey execution', and 'county smoking survey plan specification'

### ISSUE THREAD

**Issue by dillerm** [ufbmi/OMRSE#108]
editor preferred term: county smoking survey data
alternative terms: none
textual definition: A data item that is the specified output of a county smoking survey execution.
definition source: none
logical definition: subclass-of survey data (OMIABIS, OBIB); is_specified_output_of some county smoking survey execution (equivalent class)
example of usage: The Alachua county smoking survey data.
term editor: Mathias Brochhausen
contributors: Hansi Zhang, Jiang Bian, Clint Dowland, Matt Diller, William R. Hogan, Sarah Bost

editor preferred term: county smoking survey execution
alternative terms: none
textual definition: A survey execution that realizes the concretization of a smoking survey plan specification that is stratified by county.
definition source: none
logical definition: subclass-of survey execution; realizes some (concretizes some county smoking survey plan specification) (equivalent class)
example of usage: The Alachua county smoking survey execution.
term editor: Mathias Brochhausen
contributors: Hansi Zhang, Jiang Bian, Clint Dowland, Matt Diller, William R. Hogan, Sarah Bost

editor preferred term: county smoking survey plan specification
alternative terms: none
textual definition: A survey plan specification that aims to collect information about the smoking behavior or lack thereof of a population on a county level. Concretization of a smoking survey plan that is stratified by county.
definition source: none
logical definition: subclass-of survey plan specification
example of usage: The Alachua county smoking survey plan specification.
term editor: Mathias Brochhausen
contributors: Hansi Zhang, Jiang Bian, Clint Dowland, Matt Diller, William R. Hogan, Sarah Bost

**Comment by sjbost** [comment]
Revise textual definition of 'county smoking survey data' as follows: A **survey data** that is the specified output of a county smoking survey execution.

**Comment by CDowland** [comment]
"Data" is plural, so I'm not sure about that "A" at the beginning.

Here's are the requests I submitted to OGMS, which are consistent with the most recent version of the spreadsheet:

https://github.com/OGMS/ogms/issues/143

**Comment by sjbost** [comment]
We probably don't need "a" at the beginning. But since Matt submitted these terms before the last Aim 2/4 meeting and before you updated the spreadsheet, I just wanted to make sure we use **survey data** instead of data item.
