### ISSUE TITLE
Term request: Language literacy competence

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/OMRSE#109]
Literacy is different from a mere linguistic competence.  See attached proposal.
[linguistic literacy term request for ogms.xlsx](https://github.com/ufbmi/OMRSE/files/4927760/linguistic.literacy.term.request.for.ogms.xlsx)

**Comment by mbrochhausen** [comment]
I agree that literacy is different from competence. Based on the definition
I am not sure I would understand what precisely we mean by literacy. Is
there a description (not genus differentia) that would help my
understanding the intended meaning?
Thanks!

**Comment by CDowland** [comment]
Perhaps I'm focusing on the label too much, but I take it that "literacy" is typically used to refer to an ability realized in reading and writing. However, neither of those activities is mentioned in the definition or comments. So, I am also a little confused about what this is intended to represent. Is it something like fluency (as opposed to mere competence) that this is meant to capture, or is that way off?

**Comment by hoganwr** [comment]
It's more than just reading and writing.  It's also understanding (which is
a bit more than mere reading, I think).  Also, it involves cultural and
other competencies.  i explain a lot of this in the attached term request
document in the comments.

In terms of parent class, it's a child of disposition, so I am not sure I
fully understand the issue there.

I didn't try to comprehensively list all of the disposition parts it has,
because (1) I don't need/want to define those too and (2) I wouldn't be
confident I listed them all.

Finally, as I note in one of the aforementioned comments, literacy also
connotes doing something with language.  Hence the "personal goal" aspect.

FYI: the term request spreadsheet is attached to the original issue
request, not this email.
