### ISSUE TITLE
Burn patient - How to model burns?

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#11]
Once we decide how to model injuries, we will need to request a subclass for burns in the appropriate ontology.

**Comment by aellenhicks** [comment]
'burn', 'thermal burn', 'electrical burn', 'chemical burn', and 'radiation burn' were requested in OGMS.

**Comment by aellenhicks** [comment]
The following response was received from OGMS.
"I think 'burn’ (or should it be 'burns’?) is a good high level term for OGMS. But the sub-classes listed below probably belong in a sub-domain ontology that extends OGMS.
cheers
Sivaram"

**Comment by aellenhicks** [comment]
Followed up with OGMS issue #93.

**Comment by sjbost** [comment]
'Burn patient role' is in OMRSE but no axiomatic definitions besides super class. Closing issue.
