### ISSUE TITLE
New term request: disclosure of residence

### ISSUE THREAD

**Issue by dillerm** [ufbmi/OMRSE#126]
label: disclosure of residence
definition: A social act that creates an information content entity that is about some geographical region in which an individual lives.
term editor: Matthew Diller
contributors: Mathias Brochhausen, Sarah Bost, William R. Hogan, S. Clint Dowland, Hansi Zhang

**Comment by hoganwr** [comment]
Would add a comment:

Note that the individual might not have a housing unit in which they live, so we do not make explicit reference to one.  Also, the geographical region can be specified at finer (census block) or greater (nation) granularity.

**Comment by hoganwr** [comment]
But overall, I think the definition is good and approve.

**Comment by sjbost** [comment]
@mbrochhausen What do you think?

**Comment by sjbost** [comment]
@mbrochhausen Would you please review this NTR? In our Moonshot meeting two weeks ago, you had agreed to review by COB today.

**Comment by mbrochhausen** [comment]
I propose: "A social act that creates an information content entity that is about some geographical region in which a human being dwells."

**Comment by hoganwr** [comment]
+1
