### ISSUE TITLE
Organizations and roles

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#14]
We need to model organizations the their relations to roles involved in them.

**Comment by hoganwr** [comment]
Being discussed on Wiki: [What is the relation between a role and the organization that creates sanctions confers it?](../What-is-the-relation-between-a-role-and-the-organization-that-creates-sanctions-confers-it%3F)

**Comment by mbrochhausen** [comment]
Bill,

the link you sent doesn't seem to work.

Thanks,
Mathias

**Comment by hoganwr** [comment]
Works now.

**Comment by hoganwr** [comment]
To be clear - link on the tracker works now.  Link in the email will not.

**Comment by mbrochhausen** [comment]
Thanks. Works fine.

**Comment by mbrochhausen** [comment]
I read the wikipage. The example you bring up in #Option1 involves a document act and is certainly relevant. I also agree that there are other roles which are not created by contracts.

**Comment by aellenhicks** [comment]
Option #2 has been added to the wiki and provisionally implemented in OMRSE.
