### ISSUE TITLE
MIREOT code OMRSE and Repo files

### ISSUE THREAD

**Issue by matentzn** [ufbmi/OMRSE#152]
Hey @dillerm !

For reference, would you mind sharing the commands you are using to `MIREOT` information from external ontologies, and merge them into omrse?

Another question: I can see this is the current import structure:

- omrse.owl
   - education.owl
      - omrse-core.owl (importing some old fragment of BFO, IAO, PNO, and d-acts (IAO subsets I assume))
   - language.owl
      - omrse-core.owl

Is it fair to say that:
- omrse.owl is the main ontology which imports everything
- omrse-core contains the core omrse concepts
- education and language are the two primary specialised components of omrse, which depend on the core terms.
- what we call OMRSE (the whole ontology) are all of the above together (core, language, education).

This leaves the following file generally disconnected:
- language-individuals.owl (importing language.owl)

What is its role in OMRSE?

**Comment by dillerm** [comment]
We use the MIREOT plugin for Protege, the repo of which can be found here: https://github.com/UAMS-DBMI/MIREOT-plugin.

Yes, that is the import structure for OMRSE and each of the statements in the four bullet points below that are correct. 

The reason for why we do not import language-individuals.owl into any of the other files is that we want to keep the language individuals demarcated from language classes. @hoganwr might have a more detailed explanation than that.

**Comment by matentzn** [comment]
Thank you @dillerm !

**Comment by hoganwr** [comment]
Nothing further to do here.  We have, incidentally, moved to the OBO ODK methodology for maintaining OMRSE, so MIREOT no longer goes through the Protege plugin, but instead via the ODK process.
