### ISSUE TITLE
How is hospital organization different from OBI's hospital

### ISSUE THREAD

**Issue by alanruttenberg** [ufbmi/OMRSE#153]
http://purl.obolibrary.org/obo/OMRSE_00000056
vs
http://purl.obolibrary.org/obo/OBI_0000844

**Comment by mbrochhausen** [comment]
Alan,

if you click on the links you can see that the OMRSE term has an axiom that
links it to hospital role. It seems that the OBI term does not rely on a
role, but I might be wrong.

Hope that helps.

Best,
Mathias

**Comment by mbrochhausen** [comment]
PS: I also notice that the OBI term does not allow to differentiate between
a hospital and a clinic. Something that the OMRSE term allows via the
ontological commitment to the hospital role:
http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/OMRSE_00000054

Best,
mathias

**Comment by alanruttenberg** [comment]
It allows one to differentiate, but OBI didn't. It's a reasonable request for OBI to change the label to better match the definition, or to ask whether the intention was to include clinics or not, in which case they might amend the definition.  Regardless, it would appear that OBI:hospital is superclass of hospital organization and clinic organization. However, there is no clinic organization only clinic facility. Also the hospital role definition looks as promiscuous as OBO's

**Comment by alanruttenberg** [comment]
In any case, not worth much more time on this. I noticed while reviewing a paper and thought it was worth mentioning.

**Comment by mbrochhausen** [comment]
I am not sure what you mean by "OBO's".

Thanks,
Mathias

**Comment by mbrochhausen** [comment]
To move this argument forward, I am going to assume you meant to say that
OMRSE definition of hospital role is as promiscuous as OBI's definition of
hospital organization.
If that is not what you meant please disregard the following:

I totally and unreservedly respect your opinion on that, but I disagree.
You seem to agree that the hospital role definition in OMRSE allows for a
specificitate that the hospital organization definition in OBI does not (at
least that is how I understand your reply). Hence, I do not believe that it
is justified to say that both definitions are of exactly the same
promiscuity. Do I claim that the definition of hospital role is perfect?
No, but it is better than the one of hospital organization in OBI.
However, I think that the discussion regarding the comparison of the two
initial terms is pretty much exhausted. I propose to close this issue
tracker item and, if that is something you want to follow up on, create a
new issue tracker item to discuss improvement of the hospital role
definition. I am looking forward to your ideas of how to improve the text
of the definition.

Let me know whether that's ok with you.

**Comment by mbrochhausen** [comment]
Here is a proposal from my side that will take care of cases of promiscuity
issues with the OMRSE definition that I can think off:
" A healthcare provider role that inheres in an organization and, if
realized, is realized by the employment of human beings bearing a health
care provider role, admitting patients and providing inpatient and
outpatient care to those patients.

Let me know whether that meets your approval. If not, I am more than happy
to consider edits to the text of the definition.

**Comment by alanruttenberg** [comment]
OBOs was typo and you correctly understood that I meant OBI's

I used the term promiscuous as attempt at lightness. No offense I hope.  My concern that the definition in OMRSE allowed the same set of entities to be classified as hospital organization as OBI did.  The thing missing for me was how to differentiate clinic from hospital. The part that seems to do that is "providing inpatient and outpatient care to those patients"

I'm inferring that clinic is differentiated in that it only has outpatient care? And that the AND in the definition means must have both inpatient and outpatient care?

Assuming I've got that right, I  questioned whether a) all hospitals have outpatient care and b) whether all clinics don't have inpatient care? Since, if true, the differentiation doesn't work. 

My gut is that the answer to (a) is no they don't (b)  they don't.

If those answers were correct the two could be distinguished by: 
- hospital has inpatient care
- clinic has outpatient care but not inpatient care.

**Comment by mbrochhausen** [comment]
No offence taken.

I see your point and I agree that that needs to be addressed. I am certain
that you are correct and the answer to (a) is no. I am not sure sure the
answer of (b) is no. Most of my experience with clinics derives from my
work on trauma centers, the lower levels of which include clinics and there
the lack of inpatient care is a common feature of clinics. I will ask Bill
Hogan for advice on this matter.

Best,
Mathias

**Comment by LightGrenadier** [comment]
We will remove "AND outpatient" as a criterion for hospital.
