### ISSUE TITLE
Social Determination of Health

### ISSUE THREAD

**Issue by linikujp** [ufbmi/OMRSE#156]
Hi OMRSE developers,
I am wondering how much is the OMRSE cover the current thinking of SoDH in COVID19.
Is there a list?
Thanks,
Asiyah

**Comment by hoganwr** [comment]
Hi Asiyah.  We are working on SDoH generally.  That led to the classes on
education.  We started work on economic things, but that has regrettably
stalled out, and has yet to result in new classes in OMRSE.  We do not have
a project looking at the SDoH that are especially relevant to COVID (other
than race, ethnicity, and gender, which we are still currently working
on).  So we do not have a list of the subset of SDoH that are most relevant
to COVID-19. We would welcome anyone working in that area to collaborate on
them.

**Comment by linikujp** [comment]
Thank you, Bill!
I am involved in N3C's SoDH related workinggroup. It seems there will be
some concepts or a list of things that the group is considering. I will
keep you posted.

Race, ethnicity and gender are very important terms. I am wondering if you
have mappings to USCID, HL7, CDMs or other standards etc.

Thanks,
Asiyah

**Comment by linikujp** [comment]
Please check on the HL7 Gravity Project. https://confluence.hl7.org/display/GRAV/The+Gravity+Project
Please let me know if you'd like to follow their terminologies and put into the OMRSE. I try to join their calls.
Thanks,
Asiyah

**Comment by CDowland** [comment]
@linikujp Thanks for sharing this. There's a lot to sort through at that link, and while I found a page titled "Terminology and Ontology Working Group Progress Notes," the terms there seem to be in the domain of designing clinical trials or other studies.  

Could you point us in the direction of something more specific regarding the Gravity Project's ontology or terminology work in the realm of SDoH?

**Comment by linikujp** [comment]
Hi Clint,
The HL7 Gravity group is actively developing SDoH related code system. For
ontology development,  I am now with another group who is related with the
HL7 Gravity group for SDoH related ontology. I am currently working with a
domain expert for child welfare ontology. If you are interested,  welcome
to join us.

Thanks,
Asiyah

**Comment by LightGrenadier** [comment]
We are closing this issue. If new term requests arise from HL7 Gravity please do not hesitate to add them to the issue tracker in the future. Thank you.
