### ISSUE TITLE
'admission process' equivalent axioms may be incorrect

### ISSUE THREAD

**Issue by johnwjudkins** [ufbmi/OMRSE#161]
[admission process](http://purl.obolibrary.org/obo/OMRSE_00000201) has two equivalent axioms. One of these is "before some 'patient discharge'", which declares _any_ process occurring before patient discharge to be an admission process.

I think what was meant was one equivalent axiom:
"(starts some 'inpatient encounter') and (before some 'patient discharge')".

**Comment by matentzn** [comment]
Good catch! As an aside, I would also mention that there are very few cases where having more than one equivalent class axiom is appropriate. `ROBOT report`, for example, will print a warning in this case.

**Comment by matentzn** [comment]
Looking at this again, I believe this is also just false 

It is true that the admission process `starts some patient encounter` and `happens before` some discharge, but the encounter is not fully defined by these two facts. My suggestion is to move them as subclass of axioms instead.

**Comment by hoganwr** [comment]
We fixed this issue in the conversion of OMRSE to ODK. The two axioms are now superclass axioms of admission process. Closing.
