### ISSUE TITLE
Four terms now appearing with either no parent class or incorrect parent class

### ISSUE THREAD

**Issue by CDowland** [ufbmi/OMRSE#162]
Both _health care encounter_ and _injury_ are showing up as top level terms, i.e., as siblings of _entity_.

Also, while _home health care encounter_ and _post-acute health care encounter_ still have _health care encounter_ as a parent, they also have _occurrent_ as a parent. 

I'm not sure what caused this, but I know it is a recent change. I don't mind fixing it myself, but I still need to familiarize myself with our new method of pushing changes before doing so.

**Comment by matentzn** [comment]
Interesting, I will watch here what you find; any recent changes to the classification will be due to reasoning - so most likely (that's where I would look), wrong equivalent class definitions! Could be other axioms as well. I would: open omrse-edit.owl, run the reasoner and see what it says in the inferred hierarchy. I will keep watching!

**Comment by CDowland** [comment]
None of them have equivalence axioms, and _injury_ and _health care encounter_ now lack any axioms at all.

I think that might explain why the other two ended up with _occurrent_ as a parent class. They each have an _occurs in_  axiom, and that property has _occurrent_ as its domain. So, since the reasoner does not "know" that their parent class, _health care encounter_ is supposed to be an occurrent, it may have inferred _occurrent_ as another parent for them.

I have just noticed that _skilled nursing encounter_, which is also child of _health care encounter_ has also been given a second parent, _process_. Similar to the above, it has a _realizes_ axiom, which requires a process for the domain, so without _health care process_ having a parent, the reasoner could have inferred from the axiom that _skilled nursing encounter_ must be a process.

If these are the correct explanations, then the remaining question is why/how _injury_ and _health care encounter_ lost their axioms. 

It may be worth noting that OMRSE does not include the classes that OGMS has as parent classes for either _injury_ or _health care encounter_. I do not recall whether it had them previously. I want to say it had _disorder_ (OGMS's parent for _injury_), but I don't recall it having _health care process_ (OGMS's parent class for _health care encounter_).

**Comment by matentzn** [comment]
> It may be worth noting that OMRSE does not include the classes that OGMS has as parent classes for either injury or health care encounter. I do not recall whether it had them previously. I want to say it had disorder (OGMS's parent for injury), but I don't recall it having health care process (OGMS's parent class for health care encounter).

I think @dillerm did a quite through check so I would doubt it - but they would be easy to add.

> It may be worth noting that OMRSE does not include the classes that OGMS has as parent classes for either injury or health care encounter. I do not recall whether it had them previously. I want to say it had disorder (OGMS's parent for injury), but I don't recall it having health care process (OGMS's parent class for health care encounter).

This will most likely be due to `reduce`. The full spec for the ontology release file can be found [here](https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-2-full-required). What reduce does is that it removes redundant axioms, that is axioms that are _already implied_. In the case of missing existential restrictions (they should show up when you open omrse-edit.owl though!), this is usually if a parent class already has the axiom. In this case, protege would show the axiom in the `SubClassOf (Anonymous Ancestor)` section.

**Comment by dillerm** [comment]
I'm looking at an old version of OMRSE-core that I have on my personal computer and it looks like we never imported _disorder_ or _health care process_ from OGMS.

**Comment by CDowland** [comment]
But then we must have added them as subclasses of more general classes (_injury_ under _disposition_, _health care process_ under _process_), so something caused them to lose the parent classes we'd given them within OMRSE.

I've tried running a reasoner on omrse-edit. So far, this hasn't sorted out the above issue for me, but plenty of other issues show up. Several classes that should not be equivalent are inferred to be equivalent to each other (owl:Thing, _entity_, _continuant_, _generically dependent continuant_, _information content entity_, _data item_, and _survey data_ are all inferred to be equivalent to one another), and several classes are inferred to be equivalent to owl:Nothing (such as _occurrent_ and all its subclasses). None of this happens when running the same reasoner on an old version of omrse-core. 

I also noticed we have _geographic location_ as both a class and an individual, which is of course very bad. Similarly, _defined class_ shows up as an individual. While it does not also show up as a class, it is used in the equivalence axiom for _denotator type__, which is also the class is it asserted to be an instance of. But it is this way in the old version of omrse-core, and as I said above, that version does not infer all the weird results as the new version, so while these individuals need to be corrected, they do not seem to be the source of the problem.

**Comment by matentzn** [comment]
I am looking into this now; you are using HermiT?

**Comment by CDowland** [comment]
@matentzn Yes, that's the one I used.

**Comment by matentzn** [comment]
@CDowland, my sincerest apologies. We had a last second switch in OMRSE removing OMIABIS in favour of OBIB according to instructions from @mbrochhausen and ELK-based QC did not release that we were still importing the OLD (and severely broken) OMIABIS. I replaced it now correctly by OBIB in #163 

Please review and merge that - and keep your observations flowing. Maybe there are other errors - due to refreshed axioms in the imports! I will help you chase don't the faulty axiomatisation if so.

**Comment by CDowland** [comment]
In addition to the same issues I noted before still being present, there are now two more terms that are appearing as top-level terms: they are _biobank description in english_ and _sample collection identifier_.

**Comment by matentzn** [comment]
I wanted to make sure that the most pressing issue (the broken import) was fixed first before I tackle the others:

> Both health care encounter and injury are showing up as top level terms, i.e., as siblings of entity.

The reason why these terms are no longer classified as such is that the associations to BFO classes are not imported by the OGMS module. I have added this now to the config, so injury is now under `material entity` and `health care encounter` under planned process.

> Also, while home health care encounter and post-acute health care encounter still have health care encounter as a parent, they also have occurrent as a parent.

Only in the edit file! In the release (omrse.owl) you only see the health care encounter:

![image](https://user-images.githubusercontent.com/7070631/115523881-727bd400-a285-11eb-92f6-aa11428db469.png)

> I have just noticed that skilled nursing encounter, which is also child of health care encounter has also been given a second parent, process. Similar to the above, it has a realizes axiom, which requires a process for the domain, so without health care process having a parent, the reasoner could have inferred from the axiom that skilled nursing encounter must be a process.

Same as above: 
![image](https://user-images.githubusercontent.com/7070631/115524099-abb44400-a285-11eb-8b89-1b4a49443c75.png)

It is important that your consider omrse.owl primarily - which is what your users will see - and not just omrse-edit.owl. The latter is really the editors file: many redundant subsumptions (such as the ones about occurrent) are being stripped away during the release.

@CDowland all the fixes are currently here:
https://github.com/ufbmi/OMRSE/pull/166/files

I would suggest that 
- [ ] @dillerm reviews and merges the two open pull requests
- [ ] @dillerm makes a new release
- [ ] @CDowland continues his review. In the meantime, I made a test release for you [here](https://github.com/matentzn/OMRSE/blob/master/omrse.owl) that you can download and open in Protege. This is how the release will look like after @dillerm has done the above.

Let me know if that sounds good for you!

**Comment by CDowland** [comment]
> Only in the edit file! 

> It is important that your consider omrse.owl primarily - which is what your users will see - and not just omrse-edit.owl. The latter is really the editors file: many redundant subsumptions (such as the ones about occurrent) are being stripped away during the release.

Yes, but it was not only in the edit file. The issues seem to be fixed now, but I was not viewing omrse-edit when I observed those problems.

**Comment by matentzn** [comment]
Maybe the problem was due to this broken import then! Are all your other concerns addressed @CDowland ?

**Comment by CDowland** [comment]
@matentzn Yes, so far as I can tell. Thanks for your help! I will go ahead and close this issue.
