### ISSUE TITLE
RTR: preferred language ICE

### ISSUE THREAD

**Issue by CDowland** [ufbmi/OMRSE#175]
Class: preferred language information content entity

Term IRI: http://purl.obolibrary.org/obo/OMRSE_00000197

Current Textual Definition: An information content entity that (i) is about some person, some language, and some linguistic competence; and (ii) conveys the language with which that person prefers to communicate within some given context.

Proposed Textual Definition: An information content entity that is about some person and some language, and that conveys the language with which that person prefers to communicate within some given context.

Current Axioms:
- is about some linguistic competence
- is about some language
- is about some (material entity and (bearer of some linguistic competence))

Proposed Axioms [same as above, minus the first one]:
- is about some language
- is about some (material entity and (bearer of some linguistic competence))

Explanation: It has been pointed out to me (by a co-author of a paper) that the preferred language ICE may not always be about a linguistic competence. There are scenarios in which a person might have to rely on communicating in a language for which they lack a competence. If my best chance at communicating with my provider in a foreign country is using Google Translate to communicate via a language for which I have no competence, that language is my preferred (chosen) one for that encounter. 

I think in the future it may be useful to represent primary language in addition to preferred language, especially since the two might be useful together. If so, and if there is later a term 'primary language ICE,' then I think an axiom like the one removed here would be a good one to include, and it would be an important distinction between primary and preferred. 

@mbrochhausen Since you are the definition editor for this term, I wanted to check what your thoughts on this are.

**Comment by mbrochhausen** [comment]
I agree with the proposed changes.

**Comment by CDowland** [comment]
Closing because this change is among those included in #176.
