### ISSUE TITLE
exporting subsets of ontologies in OMRSE

### ISSUE THREAD

**Issue by wdduncan** [ufbmi/OMRSE#186]
@matentzn This mainly for my edification (and anyone else who is interested) :)

In the repo, the `go` import only includes the hierarchy:
```
* biological process
  *  behavior
```
However, I can't tell from the `omrse-odk.yaml`, `Makefile`, or `omrse.Makefile` how this extract is happening. 

Can you enlighten me?

cc @hoganwr @matentzn @dillerm @CDowland @mbrochhausen

**Comment by matentzn** [comment]
This is the key:

https://github.com/ufbmi/OMRSE/blob/master/src/ontology/omrse-odk.yaml#L14

It configures all the modules for OMRSE to be simple ROBOT filter modules (not, like in many other ontologies we maintain, SLME). This means that unless @hoganwr and team explicitly import a term (by adding it to this template: https://github.com/ufbmi/OMRSE/blob/master/src/templates/external_import.tsv), it wont appear! (parents are _not_ automagically included in the filter module)
