### ISSUE TITLE
RO:'deprecated_has active participant' needs to be replaced also in the axioms using it

### ISSUE THREAD

**Issue by StroemPhi** [ufbmi/OMRSE#187]
Hi, 
I just wanted to let you know that the deprecation of the object property [RO:'has active participant'](http://purl.obolibrary.org/obo/RO_0002218) has not been reflected in the axioms of the OMRSE classes in which it was used, which are: ['human role within an organization'](http://purl.obolibrary.org/obo/OMRSE_00000086), ['early childhood education plan specification'](http://purl.obolibrary.org/obo/OMRSE_00002033), ['insurance policy'](http://purl.obolibrary.org/obo/OMRSE_00000091) and ['job role'](http://purl.obolibrary.org/obo/OMRSE_00000077). The import module of RO seems to be up to date, as this OP is owl:deprecated=true, but the replacement in the axioms must be done manually, I guess.

:wink:

**Comment by StroemPhi** [comment]
Sure, it was replaced by [causal agent in process](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002500). Although, I was wondering whether using one of its subproperties [involved in](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002331&lang=en&viewMode=All&siblings=false#) makes sense in some of the cases like job role.

**Comment by hoganwr** [comment]
Thank you!  We'll investigate the new OPs and handle the updates
accordingly.
