### ISSUE TITLE
Issue regarding role in human social process

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#194]
This issue has been posted to d-acts, but I think it needs to be resolved in OMRSE:
https://github.com/d-acts/d-acts/issues/35

**Comment by dillerm** [comment]
Current proposal on the table is to change the definition to "A role that inheres in some entity that is realized in some social act." This is slightly different than Jonathan's proposal in that is changes "a social act" to "some social act" to allow for one or more social acts to realize this role.

**Comment by dillerm** [comment]
@wdduncan this sounds good to me; we can change it to "...a social act."
