### ISSUE TITLE
Suggestion to remove OMRSE_00000124: residential function

### ISSUE THREAD

**Issue by CDowland** [ufbmi/OMRSE#196]
[OMRSE: residential function](http://purl.obolibrary.org/obo/OMRSE_00000124) has no annotations.  And it is superfluous because of [OMRSE: residence function](http://purl.obolibrary.org/obo/OMRSE_00000075). 

The only term that uses _residential function_ is [OMRSE: residential health care facility](http://purl.obolibrary.org/obo/OMRSE_00000108), in its _bearer of_ axiom. That could be updated to use _residence function_ instead, and then _residential function_ could be obsoleted without any trouble or loss.

**Comment by dillerm** [comment]
From 4/5 meeting: We will deprecate this term, replace any axioms that use it with the correct term, and add a replaced-by annotation to point this term to the correct one.
