### ISSUE TITLE
NTR: birth attendant role

### ISSUE THREAD

**Issue by johnwjudkins** [ufbmi/OMRSE#202]
For new term requests, please provide the following information:

## Preferred term label

birth attendant role

## Synonyms

skilled birth attendant role

## Textual definition

A health care provider role that is realized in maintaining the health of women and newborns during pregnancy, birth, and postpartum.

## Suggested parent term

health care provider role

## Attribution

0000-0001-6595-0902

**Comment by LightGrenadier** [comment]
Proposed definition on 4/5 OMRSE meeting: A health care provider role that is realized in maintaining the health of a human being during their pregnancy and both them and the neonate during labor, delivery, and postpartum.
