### ISSUE TITLE
NTR: Four additional subclasses of 'highest level of education data item' 

### ISSUE THREAD

**Issue by CDowland** [ufbmi/OMRSE#238]
This NTR is for four subclasses of 'highest level of education data item.'  The first is for cases in which it is only known that the person's highest level of education is something below high school diploma/equivalent, but the level is not further specified. The second and third are for when the data reflect that a person started but did not complete college or high school, respectively. The fourth is for when the person's highest level of education is high school completion or the equivalent.

# Term 1/4:

## Preferred term label
highest level of education is below high school completion or equivalent data item

## Textual definition
A highest level of education data item that represents the fact that an individual in the United States is has not achieved a level of education that is equivalent to or higher than a complete high school education.

## Suggested parent term
[highest level of education data item](http://purl.obolibrary.org/obo/OMRSE_00002045)

## Attribution
ORCID: 0000-0003-1909-9269

# Term 2/4:

## Preferred term label
highest level of education is some college data item

## Textual definition
A highest level of education data item that represents the fact that the highest level of education achieved by an individual in the United States is completion of some undergraduate coursework, but without attaining an undergraduate degree.

## Suggested parent term
[highest level of education data item](http://purl.obolibrary.org/obo/OMRSE_00002045)

## Attribution
ORCID: 0000-0003-1909-9269

# Term 3/4:

## Preferred term label
highest level of education is some but not all high school data item

## Textual definition
A highest level of education data item that represents the fact that the highest level of education achieved by an individual in the United States is completion of some high school coursework, but without attaining a diploma or equivalent.

## Suggested parent term
[highest level of education data item](http://purl.obolibrary.org/obo/OMRSE_00002045)

## Attribution
ORCID: 0000-0003-1909-9269

# Term 4/4:

## Preferred term label
highest level of education is completion of high school or equivalent data item

## Textual definition
A highest level of education data item that represents the fact that the highest level of education achieved by an individual in the United States is completion of high school or equivalent.

## Suggested parent term
[highest level of education data item](http://purl.obolibrary.org/obo/OMRSE_00002045)

## Attribution
ORCID: 0000-0003-1909-9269

**Comment by hoganwr** [comment]
We discussed at OMRSE meeting on August 7, and agreed to create these classes as defined.
