### ISSUE TITLE
unemployed role

### ISSUE THREAD

**Issue by dwelch2101** [ufbmi/OMRSE#29]
initial proposed definition:

“An unemployed role is a human social role that is conferred by the U.S. Census Bureau and is realized by a person who is not currently working, is currently available for work, and has made active efforts to find employment at some time during the past four weeks. A person who is waiting to be recalled from temporary layoff also realizes an unemployed role, regardless of whether or not that person is actively searching for work.”

definition source: http://www.census.gov/cps/about/cpsdef.html

**Comment by aellenhicks** [comment]
Here is a proposed new definition.

“A US Census unemployed role is a human social role that inheres in a human who is legally eligible to work, is conferred by the U.S. Census Bureau, and is realized by the bearer not working and either making active efforts to find employment in the four weeks prior to the reference week or waiting to be recalled from temporary layoff.”
