### ISSUE TITLE
Add typology of health care facilities from PCORNet CDM

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#32]
Non-Acute Institutional Stay: Includes hospice, skilled nursing facility (SNF), rehab center, nursing home, residential, overnight non-hospital dialysis, and other non-hospital stays.

Ambulatory Visit: Includes visits at outpatient clinics, physician offices, same day/ambulatory surgery centers, urgent care facilities, and other same-day ambulatory hospital encounters, but excludes emergency department encounters.

Emergency Department

**Comment by aellenhicks** [comment]
The definition of 'hospital facility' is : "A facility that is run by a hospital organization and is the bearer of a hospital function"

This gives rise to the following definition template: ‘x facility’ – A facility that is run by a/an x organization and is the bearer of a/an x function

Can we substitute 'x' with each of these terms?
'urgent care' - Are all urgent care facilities run by an urgent care organization?  For example, the UF has an urgent care clinic in Medical Plaza.  Is this run by an urgent care organization? Or is it only one service provided by some other kind of health care organization?  The same question applies to each of the following:

Ambulatory surgery
Hospice
Emergency department
Physician office
Outpatient clinic
Overnight dialysis
Rehabilitation
Skilled nursing
Residential
Nursing home

**Comment by hoganwr** [comment]
No the template doesn't work very well unless UF Health is at the same all of (1) hospital organization, (2) urgent care organization, (3) ambulatory surgery organization, (4) emergency department organization, etc.

In other words, if the only criterion to be an X organization is that you do X, then it works, but is weird.

UF Health is one organization that runs many different services (hospital, clinic, ED, urgent care, etc).

**Comment by mbrochhausen** [comment]
I think the template should be:
A facility that is run by a bearer of a healthcare provider organization and is the bearer of a/an x function.

It is possible that hospital facility axiom and definition need to be changed accordingly.

**Comment by aellenhicks** [comment]
Proposal - All 'health care facilities' are run by a healthcare provider organization.  If this is true, then specific facilities are distinguished by their function.

Thoughts?

**Comment by mbrochhausen** [comment]
Works for me.
