### ISSUE TITLE
term request - physician assistant role

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#34]
Proposed definition:
A role that is created by state licencing and that is realized by taking patient histories, performing physical exams, diagnosing illnesses, developing treatment plans, ordering lab tests, prescribing medications, counselling and educating patients, suturing wounds, and assisting in surgery under the supervision of a physician or a surgeon. 

Source:
http://medicine.yale.edu/pa/profession/index.aspx

Comment: 
The wikipedia article (https://en.wikipedia.org/w/index.php?title=Physician_assistant&oldid=678708609) suggests "physician assistant" is synonymous with "physician associate" (used in the UK). However, a quick survey didn't dig up any indication that physician associates are licensed to prescribe medications.

**Comment by aellenhicks** [comment]
Done
