### ISSUE TITLE
Add something corresponding to HL7 Administrative Gender 'Ambiguous' value

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#36]

**Comment by aellenhicks** [comment]
Import 'phenotypic sex', 'female', and 'male'.
Create 'intersex'

**Comment by aellenhicks** [comment]
Per a conversation with Ed Hammond, 'Administrative Gender' deliberately refers to gender, not sex.  If this is the case, 'ambiguous' probably does not refer to intersex individuals.

**Comment by sjbost** [comment]
No longer need to address.
