### ISSUE TITLE
Patient and Provider roles in OBI

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#39]
We should only have one IRI for each of these terms in OBO.

**Comment by dillerm** [comment]
Agreed and I would argue that OMRSE both is the more appropriate ontology for these classes and has better definitions for the classes. I can follow up with OBI on this.

**Comment by dillerm** [comment]
Looks like this issue has been raised in OBI's issue tracker by other people previously: see [here](https://github.com/obi-ontology/obi/issues/993) and [here](https://github.com/obi-ontology/obi/issues/1154). Looks like they decided to keep 'patient role' and create an annotation that links it to the OMRSE class, whereas for 'health care provider role' they decided to deprecate and replace it with the corresponding OMRSE class. The latter was a very recent development, so it looks like they should be implementing these changes shortly.
