### ISSUE TITLE
Imported term hierarchy

### ISSUE THREAD

**Issue by sivaramarabandi** [ufbmi/OMRSE#41]
Is it always necessary to have a full hierarchy of reused terms (URIs)? For example, [Homo](http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/NCBITaxon_9605) (NCBITaxon_9605) is a class imported from NCBITaxon and this rather long hierarchy.
<img width="650" alt="screen shot 2016-02-21 at 6 59 10 am" src="https://cloud.githubusercontent.com/assets/7880471/13202707/db625a3e-d869-11e5-8129-86d4111c6c0d.png">

Most of these terms are not relevant to the domain of OMRSE and detract from its focus. 

**Proposal**:  collapse the hierarchy by asserting:
       http://purl.obolibrary.org/obo/NCBITaxon_9605    (Homo sapiens)
                   subClassOf   http://purl.obolibrary.org/obo/OBI_0100026    (Organism)

**Comment by aellenhicks** [comment]
Fixed
