### ISSUE TITLE
Term request: anesthesiologist role

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#42]
proposed subclass to: physician
proposed definition: A physician role that is borne by a human being, which is also bearing a physician role, and is realized by providing pain relief during and after surgery.

**Comment by dillerm** [comment]
You may want to broaden the definition a bit since anesthesiologists have important roles outside of surgery, too. For example, they may administer sedatives to patients to decrease anxiety or suppress motor function, or they may administer pain relief for non-surgical procedures. In addition, their role in the operating room also includes controlling the level of consciousness in patients. As such, it may be prudent to change the last part of the definition to "...and is realized by administering temporary general or local suppression of sensory or motor nerve function during some health care encounter."

**Comment by mbrochhausen** [comment]
Fully agree with dillerm.

Change proposed definition to : "A physician role that is borne by a human being, which is also bearing a physician role, and is realized by administering temporary general or local suppression of sensory or motor nerve function during some health care encounter."

**Comment by aellenhicks** [comment]
Since 'physician role' will be the superclass how about the following definition?

"A physician role that inheres a human being and, if it is realized, is realized by administering temporary general or local suppression of sensory or motor nerve function during some health care encounter."

**Comment by mbrochhausen** [comment]
+1

**Comment by aellenhicks** [comment]
François Modave has pointed out that this definition would also apply to an anesthesiology nurse role. How about a definition that includes language about making descisions,
"A physician role that inheres a human being and, if it is realized, is realized by administering medication for the temporary general or local suppression of sensory or motor nerve function during some health care encounter or by making decisions independently of a supervising physician regarding the adminstration of such medication."

**Comment by mbrochhausen** [comment]
Your initial definition would not apply to anesthesiologist nurse roles, since it explicitly states it is a physician role. Assuming that nurse role and physician role are disjoint I would disagree with Francois' assessment of the situation. However, if the decision is to bring the decision making capicities in I won't stand in the way of that.

**Comment by aellenhicks** [comment]
Apologies, the differentia that distinguishes the realization conditions from those the corresponding nurse role were not explicitly articulated leaving open the possibility that the nurse role and the doctor role are realized by the same events (if realized at all).

**Comment by mbrochhausen** [comment]
Yes, I see that.

**Comment by aellenhicks** [comment]
I will create this class with the following definition if there is consensus.

"A physician role that inheres a human being and, if it is realized, is realized by administering medication for the temporary general or local suppression of sensory or motor nerve function during some health care encounter or by making decisions independently of a supervising physician regarding the adminstration of such medication."

**Comment by mbrochhausen** [comment]
+1

**Comment by hoganwr** [comment]
+1
