### ISSUE TITLE
Get OMRSE back in Ontobee

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#46]

**Comment by dillerm** [comment]
I actually noticed that it wasn't in the list of ontologies a few weeks ago; however, the ontology itself is still in Ontobee so I just assumed it was a glitch in their system. Nonetheless, I'm not entirely sure that they're aware of it. 

http://www.ontobee.org/ontology/OMRSE

**Comment by aellenhicks** [comment]
Emailed Oliver He.
