### ISSUE TITLE
Clarification on 'physiatrist role'

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#47]
Hi,

the definition of 'physiatrist role' states that it is a "health care role borne by a human being and realized by training and certification in rehabilitation medicine."

In addition, the definition source states "A physician with training and certification in rehabilitation/physical medicine."

This raises a number of questions:

1. Is the role indeed realized by participating (or providing?) the training and certification? Or should it state that it is realized by providing rehabilitation care?

2. If this is a role that can only be borne by physicians (which would make it different from a rehabilitation specialist) should that be mentioned in the textual definition (not only in the definition source)?

3. Should it be considered to be a sub-class to physician role?

**Comment by aellenhicks** [comment]
Hi,

1. This is a good point. It seems that the training and certification creates the role, but probably doesn't realize it. What do you think about the following definition?

"A physician role that is created by training and certification in rehabilitation/physical medicine and that is realized by the provision of or sueprvising of the provision of rehabilitation or physical therapy to a patient."

2. I agree.
3. Yes. I agree.

**Comment by mbrochhausen** [comment]
there is a typo in "supervising", otherwise I fully agree. Thanks for the clarification.

**Comment by aellenhicks** [comment]
Typo fixed. Definition changed and added as subclass of physician role.
