### ISSUE TITLE
Out of date OBO Library page

### ISSUE THREAD

**Issue by pbuttigieg** [ufbmi/OMRSE#48]
May need an update, still notes google code page: http://www.obofoundry.org/ontology/omrse.html

**Comment by aellenhicks** [comment]
Proposed change.

https://github.com/OBOFoundry/OBOFoundry.github.io/compare/master...aellenhicks:patch-1

**Comment by aellenhicks** [comment]
Created issue.
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/301
