### ISSUE TITLE
Coordination with ENVO over buildings

### ISSUE THREAD

**Issue by pbuttigieg** [ufbmi/OMRSE#49]
@aellenhicks 

ENVO has quite a few classes for buildings and building parts, and we've been receiving requests to extend that. Would you like to coordinate here? There seems to be overlap: I think ENVO is the right place for architectural entities, but OMRSE (and similar ontologies) are good for things like `household` which is more socially defined.

**Comment by aellenhicks** [comment]
We are very interested in coordinating. Can you email me at aehicks@ufl.edu
so we can set up a meeting?

Thanks,
Amanda

**Comment by aellenhicks** [comment]
Will coordinate. New issues can be created for specific tasks.

**Comment by pbuttigieg** [comment]
Great! looking forward to it!

**Comment by aellenhicks** [comment]
Can you please send me some proposed timed to Skype?



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by pbuttigieg** [comment]
Anytime this evening (Berlin/Paris time). I'll be online!

**Comment by aellenhicks** [comment]
I'm afraid today and tomorrow are booked solid during that time. Over the weekend or next week sometime? Also, Mark Jensen should be involved as well.


Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932<tel:%28352%29%20294-4197>
f: (352) 273-8703<tel:%28352%29%20273-8703>
aehicks@ufl.edu<mailto:hoganwr@ufl.edu>
________________________________

**Comment by pbuttigieg** [comment]
I can make time over the weekend. @mark-jensen what about you?
