### ISSUE TITLE
term request: pediatric surgeon role

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#51]
definition: A physician role borne by a human being and that, if realized, is being realized by its bearer using operative manual and instrumental techniques on preadult patients to investigate and/or treat a pathological condition such as disease or injury, to help improve bodily function or appearance or to repair unwanted ruptured areas.
superclass: surgeon role

**Comment by aellenhicks** [comment]
How about the following definition. Modifications are in bold

A **surgeon role** borne by a human being and that, if realized, **is realized by** its bearer using operative manual and instrumental techniques on preadult patients to investigate and/or treat a pathological condition such as disease or injury, to help improve bodily function or appearance or to repair unwanted ruptured areas.

**Comment by mbrochhausen** [comment]
Yes, agreed.

**Comment by aellenhicks** [comment]
Pediatric surgeon role has been added to OMRSE with the following definition: 

A **surgeon role** borne by a human being and that, if realized, **is realized by** its bearer using operative manual and instrumental techniques on preadult patients to investigate and/or treat a pathological condition such as disease or injury, to help improve bodily function or appearance or to repair unwanted ruptured areas.
