### ISSUE TITLE
Classes not under 'entity'

### ISSUE THREAD

**Issue by seljaseppala** [ufbmi/OMRSE#52]
The OMRSE OWL file contains OMRSE classes that are not under 'entity':

'ethnic identity role'
'gender identity role'
'Homo sapiens role'
'human patient role'
'identity datum'
'racial identity datum'
and their subclasses when they exist.

Is that intentional?

**Comment by aellenhicks** [comment]
What version of Protege are you using? I can't duplicate this on my machine.

**Comment by seljaseppala** [comment]
It seems that the problem is due to the fact that the URL for d-acts isn't resolving.

**Comment by aellenhicks** [comment]
Fixed. D-acts no longer imported. Classes manually placed in hierarchy in OMRSE file.
