### ISSUE TITLE
Trouble MIREOTing from and loading OMRSE using Protege Version 5.0.0 (Build beta-17)

### ISSUE THREAD

**Issue by dillerm** [ufbmi/OMRSE#57]
Not sure if this is causing problems for anyone else, but the following lines seemed to be the culprit:

> Line 3716: <<<<<<< HEAD
> Line 3884: =======
> Line 3885: >>>>>>> parent of 17f9716... added OMRSE_00000138 surgeon role class and definition.

Once I deleted these lines, I had no trouble loading the ontology from my local repository or MIREOTing from it.

**Comment by danielwelch** [comment]
I saw this on my github account notifications and am well out of the loop here, so sorry if I'm off  base.

Looks like the intention of the last commit https://github.com/ufbmi/OMRSE/commit/9da5fd5ea58d40bc410ea634d770c5dd038fb3c4 was to revert https://github.com/ufbmi/OMRSE/commit/17f9716c942795a601eef76c444e3d4e8e34c543, which added OMRSE_00000138 surgeon role. But in looking at the git diff, [the class and definition are still there](https://github.com/ufbmi/OMRSE/commit/9da5fd5ea58d40bc410ea634d770c5dd038fb3c4#diff-dcf78dc760bfd776a768ed5371afd19cL3718), and additionally there are some git conflict resoultion lines that need to be removed (as you pointed out @dillerm )

**Comment by aellenhicks** [comment]
Offending lines deleted. This also removes the unwanted class.
