### ISSUE TITLE
Will OMRSE take following terms?

### ISSUE THREAD

**Issue by zhengj2007** [ufbmi/OMRSE#62]
I am working on annotation of several clinical epidemiology studies using ontologies. I think some terms are in OMRSE scope and would like to know whether OMRSE want to take the terms. If so, I would like to work details.

Here is the list of terms:
- household wealth index
- poverty line
- socioeconomic factor
- household assets
- household identifier
- family identifier
- marital status
- family income
- education
- occupation
- job
- employment
- salary
- number of hours per day of employment
- human traveling information

**Comment by aellenhicks** [comment]
Yes, we are happy to take these. Do you have proposed definitions and/or superclasses?

**Comment by zhengj2007** [comment]
I have textual definitions for most terms. Some terms are hard to figure out how to align with BFO. I added them as ICE in our internal ontology. Would like to find a better parent in OMRSE. Will provide what I have now soon.

**Comment by zhengj2007** [comment]
Here is what we have internal.
  *   household wealth index
      * numerical household wealth index: A data item of a household's cumulative living standard represented in a numerical datum. The wealth index is calculated using easy-to-collect data on a household's ownership of selected assets, such as televisions and bicycles; materials used for housing construction; and types of water access and sanitation facilities. (parent: IAO_0000027 data item)
      * categorical household wealth index: A data item about a household's cumulative living standard represented in a categorical datum. The wealth index is calculated using data on a household's ownership of selected assets, such as televisions and bicycles; materials used for housing construction; and types of water access and sanitation facilities. (parent: IAO_0000027 data item)
  *   poverty line: A data item of income level issued annually by the Department of Health and Human Services. Federal poverty levels are used to determine your eligibility for certain programs and benefits. (parent: IAO_0000027 data item)
  *   socioeconomic factor: no definition yet (parent: IAO_0000030 information content entity)
  *   household assets: An information content entity about items that a household owns such as a car, funiture, etc.  (parent: IAO_0000030 information content entity)
  *   household identifier: A symbol that denotes a specific household. (parent: IAO_0000028 symbol)
  *   family identifier: A symbol that denotes a specific family, rather than the physical home in which they live.  (parent: IAO_0000028 symbol)
  *   marital status: no definition yet (parent: IAO_0000030 information content entity)
  *   family income: no definition yet (parent: IAO_0000030 information content entity)
  *   education level: An information content entity that is about the highest level of schooling that a person has reached. (parent: IAO_0000030 information content entity)
  *   occupation: an activity in which one engages An information content entity that is about something people are occupied with and you're not necessarily doing it to exchange for payment. (parent: IAO_0000030 information content entity)
  *   job
      * job role: A human social role realized in a process that often performed in exchange for payment. Many people have multiple job roles, such as those of parent, homemaker, and employee. (parent: OMRSE_00000001 human social role)
      * economic activity: A planned process that a person participates in exchange for payment. The job role born by the person is realized in the process. (parent: OBI_0000011 planned process)
  *   employment: An information content entity that is about employment. (parent: IAO_0000030 information content entity) Note: not define employment yet
  *   salary: no definition (parent: IAO_0000027 data item)
  *   number of hours per day of employment: A time measurement datum about number of hours per day spend at economic activity. (parent: IAO_0000416 time measurement datum)
  *   human traveling information: An information content entity that is about human traveling.(parent: IAO_0000030 information content entity) Note: not define traveling yet

Most of the terms are quick challenge to me. Would love to discuss them with OMRSE people.

**Comment by aellenhicks** [comment]
For the sake making discussions of definitions easier and to track progress, new issues have been created for class requested. This issue will be closed. Please refer to other issues for progress updates and discussion.
