### ISSUE TITLE
health care provider organization role - missing definition

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#63]

**Comment by aellenhicks** [comment]
How about the following definition?

A role that inheres in an organization is realized by the providing services in a health care encounter.

**Comment by mbrochhausen** [comment]
yes, two minor suggestions:

"A role that inheres in an organization and that is realized by the providing of services in a health care encounter."

**Comment by aellenhicks** [comment]
Thanks. The definition has been added to devel.
