### ISSUE TITLE
Create class for family identifier

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#69]
Definition proposed by @zhengj2007 in issue #62 

family identifier: A symbol that denotes a specific family, rather than the physical home in which they live. (parent: IAO_0000028 symbol)

**Comment by aellenhicks** [comment]
Do you want this to denote only families that live together? If so, we can state that denotes a group that is both a family and a household.

**Comment by zhengj2007** [comment]
It refers to a family no matter they live together or not.

**Comment by aellenhicks** [comment]
Created this class with the definition "A symbol that denotes a family" and the equivalent class description

symbol and denotes some family.

Is this sufficient?

**Comment by zhengj2007** [comment]
Yes. Thanks!
