### ISSUE TITLE
Create class for education level

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#72]
Definition proposed by @zhengj2007 in issue #62 

education level: An information content entity that is about the highest level of schooling that a person has reached. (parent: IAO_0000030 information content entity)

**Comment by johnwjudkins** [comment]
I'd like to propose a class for the schooling process. OMRSE already defines the student and school roles in reference to schooling, so I think that would fit well here. (We still would also like an information content entity about a person's highest level of schooling completed.)

Label: schooling

Definition: A planned process that realizes a student role and a school organization role and has the objective to increase the knowledge or skills inherent in the student.

Subclass axiom: realizes some 'school role' and realizes some 'student role'

Source: Wikipedia entry - education

**Comment by hoganwr** [comment]
John,

We created a class "education process" in the development version of OMRSE:
http://purl.obolibrary.org/obo/omrse/dev/omrse.owl

Have a look at the definition and see what you think.  I think the term
'schooling' implies formal education in a school (building w/a function)
setting that realizes the school role of the school organization and the
student role that is part of the school's organization role.

Bill

**Comment by johnwjudkins** [comment]
Thanks, Bill. The OMRSE definition looks good to me, especially the reference to capability, which I see is defined in MF.

**Comment by LightGrenadier** [comment]
This class is represented by http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/OMRSE_00002045
