### ISSUE TITLE
Create class for human traveling information

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#79]
Definition proposed by @zhengj2007 in issue #62 

human traveling information: An information content entity that is about human traveling.(parent: IAO_0000030 information content entity) Note: not define traveling yet

**Comment by aellenhicks** [comment]
[Here](http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000532) is a class in Apollo SV for "human travel". 

Proposed revisions

human travel information: An information content entity that is about human travel.

Superclass: IAO_0000030 information content entity
Equivalent class restriction: ['is about'](http://purl.obolibrary.org/obo/IAO_0000136) 'human travel' (http://purl.obolibrary.org/obo/APOLLO_SV_00000532)

Do you need a class that is more specific? For example, about types of travel, types of destinations, etc.? Do you need a class that is a child of 'data item'?

**Comment by aellenhicks** [comment]
Class created in devel: OMRSE_00000142.
Is this what you need?

**Comment by zhengj2007** [comment]
What you created, looks good to our project. We don't need more specific term now.
