### ISSUE TITLE
Homo sapiens is showing up as a subclass of itself 

### ISSUE THREAD

**Issue by cstoeckert** [ufbmi/OMRSE#83]
Homo sapiens is showing up as a subclass of itself on both Ontobee and NCBO Bioportal when viewed in OMRSE. Can you fix? 
We are getting this imported in OBIB when importing other terms from OMRSE using Ontofox and allAxiomsRecursively.
Thanks, Chris

**Comment by aellenhicks** [comment]
It seems this is being imported into OMRSE via PNO. I have logged an issue with PNO.
https://github.com/ProperNameOntology/proper-name-ontology/issues/3

Thanks, Amanda
