### ISSUE TITLE
leaving hospital facility

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#86]

**Comment by aellenhicks** [comment]
Create class for "leaving hospital facility".

**Comment by hoganwr** [comment]
We have 'leaving a healthcare facility after receiving care' as a class with IRI http://purl.obolibrary.org/obo/OMRSE_00000161

I don't believe we need this any further.  Closing for now.  Can start a new issue if we really need a subclass on leaving a hosiptal.
