### ISSUE TITLE
OMRSE broken ontology (important)

### ISSUE THREAD

**Issue by matentzn** [ufbmi/OMRSE#87]
Hey! I just noticed you have two bugs in your OMRSE release:

1) In line 617 there is <<<<<<< HEAD which suggests that someone manually resolved a conflict after a commit and did not clean up properly (this causes this file to be unparseable!

2) Line 885: Again this suggests manual hacking and should be carefully traced back to its source: The closing '`</owl:Class>`' Tag is missing (and maybe more)! (also causes the file to be unparseable)

Generally, be careful when you edit the text file of the ontology manually rather than with Protege. It makes always sense to open the ontology once more in Protege after editing to be sure everything is as expected.

**Comment by aellenhicks** [comment]
Thanks. I just updated this from the devel branch.
