### ISSUE TITLE
Definition of household is too permissive

### ISSUE THREAD

**Issue by cmungall** [ufbmi/OMRSE#88]
http://purl.obolibrary.org/obo/OMRSE_00000076

The OWL definition has less clauses than the text one, which is often a red flag

`((Homo sapiens or collection of humans)) and (participates in some (process and (realizes some residence function)))`

_A human or collection of humans that occupies a housing unit by storing their possessions there and habitually sleeping there thereby participating in the realization of its residence function._

The text and OWL don't mirror eachother which is often a red-flag. E.g. the text mentions a housing unit which seems key.

By both the text and OWL definition, any individual human is realizing their residence function is a household even when they are cohabiting with others. I assume this is not the intention, and that a definition along these lines should contain the concept of maximality.

Also presumably households should exist even when all the inhabitants are out at work etc, but this isn't consistent with the OWL definition.

Note that PCO has a class household

https://www.ebi.ac.uk/ols/ontologies/pco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCO_0000024

_A material entity that consists of one or more people who live in the same dwelling and also share at meals or living accommodation, and may consist of a single family or some other grouping of people._

FWIW, I prefer the more human-oriented definition style of PCO, but it still sounds alien to include "material entity" in the definition. 

I think both could do with a concept of "social unit" that is a subclass of PCO's IMHO slightly awkward "organismal entity". This would lend a logically coherent and human-friendly genus to the text definition of household. E.g. "a social unit composed of those living together in the same dwelling" https://www.merriam-webster.com/dictionary/household

It seems if we want to be complete there should also be a relationship (direct or indirect) to a class for house or dwelling, perhaps from ENVO

Either way, OMRSE and PCO should come to some agreement about boundaries of their respective ontologies, cc @ramonawalls

**Comment by ramonawalls** [comment]
The PCO definition for `household` was written before we had `organismal entity`, so it should be changed to use organismal entity as the parent. I will make a ticket for that.

I am happy to add social unit to PCO, but I need some input on defining it. I don't think social units are restricted to humans. Anything I can think of as a definition that works generally is so broad that is just ends up being the same as organismal entity.

FYI, organismal entity may be awkward, but it is pretty important to be able to talk about an entity that consists of one or multiple organisms. The creation was motived by several important use cases, including the definition of household and mapping to Darwin Core.
