### ISSUE TITLE
Change of textual definitions for 'patient role'

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#9]
OMRSE currently has two definitions for 'patient role': 
* "A human health care role that inheres in an organism [human?] as the recipient of a health care service."

* "A role borne by an organism being as the recipient of a health care service."

May 29, 2015 the following textual definition was approved by the trauma domain experts for the CAFE project.  

* 'patient' - A person who presents to a medical provider in a clinical health encounter.

In light of our domain experts' feedback I propose deleting the two current definitions and adding this one: 
* "A role borne by an organism who presents to a health care provider in a clinical encounter."

The domain experts pointed out that receiving health care services is sufficient but not necessary for being a patient.  It is necessary to present for health care services.  (If you go to the ER, and never receive health care, you realize the patient role by virtue of presenting for care.) 

The proposed definition is **broader** than the existing definitions, so current instances of OMRSE's 'patient role' will still be captured by the proposed definition.

**Comment by hoganwr** [comment]
First I'd say the presenting to the provider is the realization of the role.

Second I'm not sure realizing the role is necessary to bear it.

Bill

**Comment by aellenhicks** [comment]
Point taken. How about this?

"A role borne by an organism and that is realized by presenting to a health
care provider in a clinical encounter."

On Tue, Jun 16, 2015 at 3:46 PM, Bill Hogan <notifications@github.com>
wrote:

> First I'd say the presenting to the provider is the realization of the
> role.
>
> Second I'm not sure realizing the role is necessary to bear it.
>
> Bill
>
> On Tuesday, June 16, 2015, aellenhicks <notifications@github.com> wrote:
>
> > OMRSE currently has two definitions for 'patient role':
> >
> > -
> >
> > "A human health care role that inheres in an organism [human?] as the
> > recipient of a health care service."
> > -
> >
> > "A role borne by an organism being as the recipient of a health care
> > service."
> >
> > May 29, 2015 the following textual definition was approved by the trauma
> > domain experts for the CAFE project.
> >
> > - 'patient' - A person who presents to a medical provider in a
> > clinical health encounter.
> >
> > In light of our domain experts' feedback I propose deleting the two
> > current definitions and adding this one:
> >
> > - "A role borne by an organism who presents to a health care provider
> > in a clinical encounter."
> >
> > The domain experts pointed out that receiving health care services is
> > sufficient but not necessary for being a patient. It is necessary to
> > present for health care services. (If you go to the ER, and never receive
> > health care, you realize the patient role by virtue of presenting for
> > care.)
> >
> > The proposed definition is *broader* than the existing definitions, so
> > current instances of OMRSE's 'patient role' will still be captured by the
> > proposed definition.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ufbmi/OMRSE/issues/9>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufbmi/OMRSE/issues/9#issuecomment-112548064>.
>



-- 
Amanda Hicks, PhD
 Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932 <%28352%29%20294-4197>
f: (352) 273-8703
aehicks@ufl.edu <hoganwr@ufl.edu>

**Comment by hoganwr** [comment]
good.  so long as provider and clinical encounter are loose enough to avoid
the presumption of the formal structures and institutions of Western
civilization, I'm happy with it.  In other words, the organism need NOT
show up at an official place of business, with an organization formally and
legally registered with various gov't entities, with a person endowed by
the gov't with certain certifications based upon certain trainings and
performance on standardized exams, etc, etc.

Although all that's true when I see my PCP, it need not be true when, say,
I, who am no longer licensed or board certified, go to a friend's house to
say "holy cow, you've almost certainly got a DVT, go to the ED now".
