### ISSUE TITLE
Add facility definitions requested by Human Behaviour-Change Project

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/OMRSE#92]
Email with Word doc.  Requested definitions are below.  Can add these and refine from there.

OMRSE_00000104: Hospice facility
Suggested definition: A facility providing care for the sick or terminally ill

OMRSE_00000106: Rehabilitation facility
Suggested definition: A facility to assist in physical or addiction recovery

OMRSE_00000108: Residential facility
Suggested definition: An architectural structure in which a person or persons live

OMRSE_00000110: Outpatient clinic facility
Suggested definition: A facility to treat patients without them staying overnight, often after a hospital visit

OMRSE_00000114: Emergency department facility
Suggested definition: A facility specialising in emergency medicine and the acute care of patients who present without prior appointment, either by their own means or by ambulance

**Comment by mbrochhausen** [comment]
The genus for all these (except residential facility, which should be "facility", I guess) is probably "health care facility".
The notion that an architectural structure specializes in something sounds counterintuitive to me.

**Comment by hoganwr** [comment]
Thanks Mathias, I think I caught that in the definitions as I implemented them.  Please take a look at the development version, see what I did there, and see what you think.  I also caught that residential facility as defined is not a healthcare facility, so created a new class for that definition that is not a type of healthcare facility.

**Comment by hoganwr** [comment]
Actually I think that although I caught that (about facility specializing) but then didn't actually fix it.  How about: "A facility whose function is the provision of emergency healthcare services and the acute care of patients who present without prior appointment, having arrived either by their own means or by ambulance"

**Comment by mbrochhausen** [comment]
I like it! I was thinking along those lines, too. A question that came to
my mind was whether we actually are sure that those facilities always bear
the function, or whether they sometimes are merely designated.

In a national emergency a school house might be turned into a hospital. I
am not sure that it bears the function of a hospital, but it certainly
bears its role. Maybe that isn't a problem or I am getting it wrong, but I
think that is one thing to bear in mind.

If we go with functions as defining criteria it should be done for all
those specialized facilities to give us similar definitions.

**Comment by hoganwr** [comment]
I made these changes in the development version.  The development PURL issue has not resolved yet.  Waiting on OBO folks to merge my pull request.

**Comment by aellenhicks** [comment]
?In addition to the strangeness of saying a facility specializes, it is also strange to say a facility provides care. "Providing care for the sick or terminally ill" is both too broad for hospice. It's too broad since other facilities exist for the purpose of providing care to the sick and terminally ill. Also, the type of care can be specified further since hospice only offers palliative care. How about something like "A facility designed to provide acute palliative care to actively dying patients or to patients whose symptoms are too acute to be managed at home or in a palliative setting." Note that actively dying is different from terminally ill.?

________________________________

**Comment by hoganwr** [comment]
Verified that the changes went through for emergency department and hospice. Closing this issue.  Any further term requests or additions or edits, please log new issues.
