### ISSUE TITLE
Adding a new class: non-binary gender identity datum

### ISSUE THREAD

**Issue by pfabry** [ufbmi/OMRSE#95]
Hello,
In the context of our project at GRIIS (Sherbrooke university), we would need the following class.
Could you please inform us whether you could add them to OMRSE?

- Class: Non-binary gender identity datum
- Parent: Gender identity datum (OMRSE:00000133)
- Definition: A gender identity datum resulting from a gender identification process in which ‘non binary’ is selected based on the participant's subjective sense of gender. (or alternatively:  A gender identity datum stating that a person's subjective sense of gender is non-binary.)
- Examples of usage: ‘Non-binary’, ‘Trigender’, ‘Agender’, ‘Genderfluid’, ‘2’ (intended to refer to a non-binary gender role) 

This class is needed to represent information on the sex or gender of patients as found in medical records.

Best regards,

Paul Fabry

**Comment by hoganwr** [comment]
I checked the change into the development branch. PURL is http://purl.obolibrary.org/obo/omrse/dev/omrse.owl

**Comment by pfabry** [comment]
Great!

Thank you for your fast answer.
